### ISSUE TITLE
Gruppenauswahl mit Checkboxen fehlerhaft

### ISSUE THREAD

**Issue by riotweb** [raum2projekt/multinewsletter#2]
Wenn ich im Anmeldeformular EINE Gruppe via checkboxes anklicke, das Formular aber nicht vollständig ausgefüllt wurde, sind nach dem Absenden MEHRERE Checkboxen angeklickt.

**Comment by TobiasKrais** [comment]
In den nächsten Wochen kommt die runderneuerte Version 2.0. Dort ist der Fehler schon behoben.
