### ISSUE TITLE
csv import Probleme / Gruppenzuweisung

### ISSUE THREAD

**Issue by riotweb** [raum2projekt/multinewsletter#3]
Beim Import wurde der Status und die Gruppenzuordnung nicht importiert.
CSV Format war so:
email	     grad	           firstname	lastname	title	clang	status	createip	send_group
blabla@web.de		Vorname          Nachname 	    0	          1		1,2
Nach dem import sind alle user  gar keiner Gruppe zugeordnet

**Comment by TobiasKrais** [comment]
Ist in Version 2 behoben. Die wird in Kürze veröffenlticht.
