### ISSUE TITLE
deprecated - ereg_replace() - Fehlermeldungen ab PHP 5.3+

### ISSUE THREAD

**Issue by gseilheimer** [raum2projekt/multinewsletter#4]
Hallo,
beim Export unter USER gibt es in der CSV-Datei kein erwartetes Ergebnis außer:
<b>Deprecated</b>:  Function ereg_replace() is deprecated in <b>/kunden/xxx/focusing.cms/redaxo/include/addons/multinewsletter/functions/newsletter.inc.php</b> on line <b>255</b><br />

Sollte es noch einmal eine Überarbeitung geben, wäre die Ersetzung durch preg_replace() sehr hilfreich.

Gruß, GS

**Comment by TobiasKrais** [comment]
Danke für die Info. Wird erledigt. Braucht aber noch ein bisschen, da ein größerer Umbau ansteht.

**Comment by TobiasKrais** [comment]
In den nächsten Wochen kommt die runderneuerte Version 2.0. Dort ist der Fehler schon behoben.
