### ISSUE TITLE
Infomail on Subscribe-Request

### ISSUE THREAD

**Issue by Hans-Sachs** [raum2projekt/multinewsletter#6]
Hi raum2projekt,

is it possible to add an email-adress to be informed when new subscribers are requesting access to a Newsletter-List?

thx
Hans

**Comment by TobiasKrais** [comment]
Hi Hans,

I'm sorry. This is not planned. Go to the users list and sort the list by "Anmeldedatum". Then you know who is new.

Greetings,

Tobi

**Comment by Hans-Sachs** [comment]
Hi Tobi,
no way to place a small hack in the code?
no need to be complicated ;-)
cu & thanx
Hans

**Comment by TobiasKrais** [comment]
Hi Hans,

you can do it on your own and send me the code.

Currently I'm rewriting the Addon. May be I'll  think about it. But in case I'll decide to program it, it will take months.

Greetings,

Tobias

**Comment by TobiasKrais** [comment]
Hi Hans,

currently I'm rewriting the Addon. I can Add the function. To implement your wish, I will need 2 hours. In case you are willing to pay for it, please contact me on my website: http://www.design-to-use.de/.

Greetings,

Tobias

**Comment by TobiasKrais** [comment]
In Version 2.1.0 ist das drin. Für An- und Abmeldung.
