### ISSUE TITLE
Problems with File-Path

### ISSUE THREAD

**Issue by Hans-Sachs** [raum2projekt/multinewsletter#7]
Hi,

i found out that some Mailclients react alergic, when the image-path contains "/../". This problem comes up when i include images in the Newsletter-Article.

Example:
Problem: \<img title="Testbild" src="../files/test.jpg">
Solution: Problem: \<img title="Testbild" src="/files/test.jpg">
Can i put somewhere in the code an str_replace, or is there an other solution?

cu & thx
Hans

**Comment by TobiasKrais** [comment]
Hi Hans,

place a `<base href="https://www.myurl.com/">` in the head section. Then you can use your suggested solution.

Greetings, Tobias

**Comment by Hans-Sachs** [comment]
Hi Tobias,

Nope it still has ".." Included :-( tried your solution already

Cu
Hans

**Comment by TobiasKrais** [comment]
Hi Hans,

please use http://www.redaxo.org/de/forum/post114052.html?hilit=multinewsletter#p114052 for a discussion. Write there which text editor you use.

Greetings,

Tobias
