### ISSUE TITLE
Artikel-ID & Notices

### ISSUE THREAD

**Issue by bega011** [raum2projekt/multinewsletter#8]
Ich habe eine Fehlermeldung beim Newsletter-Anmeldeformular und zwar wird bei Formular in form action ausgegeben:
<form action="<br />
<b>Notice</b>:  Undefined property: rex_article::$articleId in <b>/html/redaxo/include/classes/class.rex_article.inc.php(126) : eval()'d code</b> on line <b>125</b><br />
/kontakt-und-service/newsletter-anmelden.html" method="post" name="subscribe" class="rex-xform">

Es scheint, dass rex_getUrl(**$this->articleId**, $REX['CUR_CLANG']) im Modul nicht richtig ausgegeben wird. Wenn ich die ID an der Stelle manuell eingebe oder es mit $this->articel_id ändere passt die Ausgabe und das Formular wird abgeschickt.
Danach kommen aber einige Notices:
Notice: Undefined variable: article_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259
Notice: Undefined variable: clang_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259
Notice: Undefined variable: article_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259
Notice: Undefined variable: clang_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259

Habe Redaxo 4.7 und PHP 5.6 im Einsatz.

**Comment by TobiasKrais** [comment]
Hi, kannst du es mal mit folgendem angepassten Modul versuchen: https://github.com/raum2projekt/multinewsletter/blob/master/modules/anmeldung-out.inc.php

Wegen den Notices: haben die Benutzer eine Sprache zugewiesen?

**Comment by bega011** [comment]
Hi Tobias, 
mit dem angepassten Modul hats geklappt. 
Die Notices sind weiter da. Und die Benutzer bekommen bei der Anmeldung automatisch eine Sprache, wenn du das meinst. Die Anmeldung und Bestätigung funktionieren einwandfrei.

**Comment by TobiasKrais** [comment]
Hi, Danke fürs Testen. Kannst du wegen den Notices mal folgende Version der Datei versuchen:
https://github.com/raum2projekt/multinewsletter/blob/master/classes/class.multinewsletter_user.inc.php

Grüße,
Tobi

**Comment by bega011** [comment]
Ok, jetzt kommen nur 2 bzw. 1 für article_id:
Notice: Undefined variable: article_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259

Notice: Undefined variable: article_id in /html/redaxo/include/addons/multinewsletter/classes/class.multinewsletter_user.inc.php on line 259

**Comment by TobiasKrais** [comment]
Hi, das ging ja schnell. Danke. Bitte versuche es mit folgender Datei:
https://github.com/raum2projekt/multinewsletter/blob/master/classes/class.multinewsletter_user.inc.php
Danke im Voraus!

**Comment by bega011** [comment]
Naja, ich bin gerade am Projekt dran :)
Also, mit der letzten Version klappt es einwandfrei.

Vielen Dank für deine Mühe!

**Comment by TobiasKrais** [comment]
Das hört man gerne. Danke für deine Hilfe!
